<a href="https://colab.research.google.com/github/Aryamaan23/ML-TOOLBOX/blob/master/Copy_of_Quiz_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Instructions
- Fill all the incomplete functions. Strictly follow the function specs. 
- Do not copy or plagiarize. IIT Kanpur has a very strict policy against plagiarism

###Download and read file

In [ ]:
### Download data from google drive. You need not mess with this code.

import requests

def download_file_from_google_drive(id, destination):
    URL = "https://docs.google.com/uc?export=download"

    session = requests.Session()

    response = session.get(URL, params = { 'id' : id }, stream = True)
    token = get_confirm_token(response)

    if token:
        params = { 'id' : id, 'confirm' : token }
        response = session.get(URL, params = params, stream = True)

    save_response_content(response, destination)    

def get_confirm_token(response):
    for key, value in response.cookies.items():
        if key.startswith('download_warning'):
            return value

    return None

def save_response_content(response, destination):
    CHUNK_SIZE = 32768

    with open(destination, "wb") as f:
        for chunk in response.iter_content(CHUNK_SIZE):
            if chunk: # filter out keep-alive new chunks
                f.write(chunk)
                
if __name__ == "__main__":
    file_id = '1e_Azf9zGvSWsDhM9PP2sfMNKC72-iWAK'
    destination = 'data.txt'
    download_file_from_google_drive(file_id, destination)

In [ ]:
with open('data.txt', 'r') as f:
  data_raw = f.readlines()

###1. Data preparation
Now the entire data is stored in the list ```data_raw```. \\
Every line in the file is a different element of the list. \\
First let us look at the first five elements of the list. \\


####1.1

Write a function that returns first five elements of the list if length of list is greater than or equal to 5 and None value otherwise.

In [ ]:
def first_five_in_list(l):
  """
  Inputs: 
  l: Python list

  Outputs:
  l_5 : python list, first five elements of list if length of list greater than 5; None otherwise
  """
  ### Your code here
  if(len(l)>=5):
    l_5=l[:5]
  else:
    l_5=None
  return l_5

In [ ]:
first_five_in_list(data_raw)

['ham\tGo until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...\n',
 'ham\tOk lar... Joking wif u oni...\n',
 "spam\tFree entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's\n",
 'ham\tU dun say so early hor... U c already then say...\n',
 "ham\tNah I don't think he goes to usf, he lives around here though\n"]

####1.2

You can see that the first five elements in our list look like this - 
<img src="https://drive.google.com/uc?id=1JnA0TxI-jWR4mJHYztnQQZZNRRTacsaa"> \\
<br>
You can clearly see that each line ends with a newline character. We want to remove these new line characters. \\
Write  a function that removes all extra newline characters (number of newline characters maybe greater than or equal to 0) at the end of any string that is passed to it.

In [ ]:
def remove_trailing_newlines(s):
  """
  Function that removes all trailing newlines at the end of it
  Inputs:
    s : string

  Outputs:
    s_clean : string, string s but without newline characters at the end 
  """
  ### Write your code here
  for i in range(len(s)-1,0,-1):
    if(s[-1]=='\n'):
      s=s[:-1]
    else:
      break
  s_clean=s
  return s_clean

In [ ]:
remove_trailing_newlines(data_raw[0])

'ham\tGo until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...\n'

If we apply ```remove_trailing_newlines``` to first element of data_raw, we get <br>
<img src="https://drive.google.com/uc?id=1vu-awFwqGC9sNgk-QgHMIamnFp6d996R"> <br>
You can see that the newline at the end has disappeared. <br>


####1.3

But we now we need to apply this function to the whole list. \\
Write a function named mapl, that takes two arguments - a function on elements of type $t$ and a list $l$ of elements of type $t$ and applies the function over all elements of the list $l$ and returns them as a list. 

In [ ]:
def mapl(f, l):
  """
  Function that applies f over all elements of l
  Inputs:
    f : function, f takes elements of type t1 and returns elements of type t2
    l : list, list of elements of type t1

  Ouptuts:
    f_l : list, list of elements of type t2 obtained by applying f over each element of l
  """
  ### Write your code here
  f_l=[]
  for i in l:
    f_l.append(f(i))

  return f_l

Now we can use mapl to apply remove_trailing_newlines to all lines in data_raw

In [ ]:
data_clean = mapl(remove_trailing_newlines, data_raw)
data_clean[:5]

['ham\tGo until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...',
 'ham\tOk lar... Joking wif u oni...',
 "spam\tFree entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's",
 'ham\tU dun say so early hor... U c already then say...',
 "ham\tNah I don't think he goes to usf, he lives around here though"]

First five elements of data_clean look like this: <br>
<img src = "https://drive.google.com/uc?id=17U7h87_7VjZs5CpRtJawHUfM5O1EztcS">

This is a dataset of text messages. We have to classify this into spam or ham. Ham means non-spam relevant text messages. More details can be found here - http://archive.ics.uci.edu/ml/datasets/SMS+Spam+Collection <br>
<br>
You can see that each line starts by specifying whether the message is ```ham``` or ```spam``` and then there is a tab character, ```\t``` followed by actual text message.
<br>
Now we need to split the lines to extract the two components - data label (```ham``` or ```spam```) and data sample (the text message).

####1.4

Write a function ```split_at_s``` that takes two strings - ```text``` and ```s```. <br>
It splits the string text into two parts at the first occurence of s. <br>
Then it wraps both parts in a tuple and returns it.

In [ ]:
def split_at_s(text, s):
  """Function that splits string text into two parts at the first occurence of string s
  Inputs:
    text: string, string to be split
    s : string, string of length 1 at which to split
  
  Outputs:
    split_text: tuple of size 2, contains text split in two (do not include the string s at which split occurs in any of the split parts) 
  """
  ### Write your code here
  text_splitted=text.split(s)
  split_text=(text_splitted[0],s.join(text_splitted[1:]))
  return split_text

In [ ]:
text='Hello World 1 2 3 4'
split_at_s(text,' ')
split_at_s(data_clean[0],'\t')

('ham',
 'Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...')

Python has a very handy feature used to define short functions called lambda expressions. This is from official python docs <br>
<img src = "https://drive.google.com/uc?id=1kBLTdhWT6SNrhlk7vYH7ql2KxcSKvu29">

Use lambda expressions and ```split_at_s``` to write a function, ```split_at_tab``` that takes only one argument - ```text``` and splits at the first occurence of ```'\t'``` character. (If you can't understand lambda expressions, just define the function in the ususal way)

In [ ]:
### Write your code here
split_at_tab=lambda text: split_at_s(text,'\t')

In [ ]:
split_at_tab(data_clean[0])

('ham',
 'Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...')

####1.5

Now apply ```split_at_tab``` function over the elements of list ```data_clean``` and assign it to variable named ```data_clean2```. 

In [ ]:
#### Write your code here
data_clean2=mapl(split_at_tab,data_clean)
data_clean2[:5]

[('ham',
  'Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...'),
 ('ham', 'Ok lar... Joking wif u oni...'),
 ('spam',
  "Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's"),
 ('ham', 'U dun say so early hor... U c already then say...'),
 ('ham', "Nah I don't think he goes to usf, he lives around here though")]

After splitting at '\t' character, one data point looks like this - <br>
<img src = "https://drive.google.com/uc?id=1TVblRl9K_4HFLOncSWZW20u3ztsfoCzY">


Now let us remove the punctuations in an sms.

In [ ]:
import string
def remove_punctuations_and_lower(text):
  """Function that removes punctuations in a text
  Inputs:
    text: string
  Outputs:
    text_wo_punctuations
  """
  return (text.translate(str.maketrans("","", string.punctuation))).lower()

####1.6

Now use the function remove_punctuations to remove punctuations from the text part of all of the tuples in ```data_clean2``` and assign it to a variable named ```dataset```

In [ ]:
### Write your code here
dataset=mapl(lambda x: (x[0],remove_punctuations_and_lower(x[1])),data_clean2)

In [ ]:
dataset[:5]

[('ham',
  'go until jurong point crazy available only in bugis n great world la e buffet cine there got amore wat'),
 ('ham', 'ok lar joking wif u oni'),
 ('spam',
  'free entry in 2 a wkly comp to win fa cup final tkts 21st may 2005 text fa to 87121 to receive entry questionstd txt ratetcs apply 08452810075over18s'),
 ('ham', 'u dun say so early hor u c already then say'),
 ('ham', 'nah i dont think he goes to usf he lives around here though')]

First 5 elements of ```dataset``` look like this now. <br>
<img src="https://drive.google.com/uc?id=19TomF6uXvsFALRsX6KLOPseKzxADMgRp">

Now let us count number of occurences of ```ham``` and ```spam``` in our dataset.

####1.7 

Write a function ```counter``` that takes two arguments - 
- a list $l$ of elements of type $t$
- a function $f: t \rightarrow u$ (means $f$ takes an argument of type $t$ and returns values of type $u$)

Counter returns a dictionary whose keys are $u_1, u_2, \ldots etc$ - unique values of type $u$ obtained by applying $f$ over elements of $l$. <br>
The values corresponding to the keys are the the number of times a particular key say $u_1$ is obtained when we apply $f$ over elements of $l$

In [ ]:
def counter(l, f):
  """
  Function that returns a dictionary of counts of unique values obtained by applying f over elements of l
  Inputs:
    l: list; list of elements of type t
    f: function; f takes arguments of type t and returns values of type u
  
  Outputs:
    count_dict: dictionary; keys are elements of type u, values are ints
  """
  ### Write your code here
  l_mapped=map(f,l)
  from collections import Counter
  count_dict = dict(Counter(l_mapped))
  return count_dict

####1.8

Write a function named ```aux_func``` that can be passed to ```counter``` along with the list ```dataset``` to get a dictionary containing counts of ```ham``` and ```spam``` 

In [ ]:
#### Write your code here
aux_func=lambda x:x[0]
counter(dataset,aux_func)

{'ham': 4827, 'spam': 747}

The counts of ```ham``` and ```spam``` as we can see are ```{'ham': 4827, 'spam': 747}```

Now let us split our dataset into training and test sets. We'll first shuffle the elements of the dataset, then we'll use 80% of data for training and 20% for testing.

####1.9

Write a function that takes a list, randomly shuffles it and then returns it. <br>
Hint: Use the random library of python - https://docs.python.org/3/library/random.html

In [ ]:
import random
def random_shuffle(l):
  """Function that returns a randomly shuffled list
  Inputs:
    l: list
  Outputs:
    l_shuffled: list, contains same elements as l but randomly shuffled
  """
  ### Write your code here
  l_shuffled=random.sample(l,len(l))
  return l_shuffled

In [ ]:
random_shuffle([1,2,3,4])

[2, 4, 1, 3]

1.10

Now split the shuffled list. Take 80% (4459) samples and assign them to a variable called ```data_train``` . Put the rest in a variable called ```data_test```

In [ ]:
### Write your code here
shuffled_list=random_shuffle(dataset)
data_train=shuffled_list[:4459]
data_test=shuffled_list[4459:]

### 2.Data Modeling
We shall use Naive Bayes for modelling our classifier. You can read about Naive Bayes from here (https://en.wikipedia.org/wiki/Naive_Bayes_classifier#Multinomial_naive_Bayes). But you don't actually need to read it, because we are going to move step by step in building this classifier.

First we need to find the probabilities $P(w_i | C)$ <br>
We read $P(A | B)$ as probability of event A, given event B. <br>
$P(w_i | C)$ is probability that word $w_i$ occurs in the sms given that the sms belongs to class $C$ where $C$ can be either ```spam``` or ```ham``` .
<br>
But we will be finding $\tilde{P}(w_i|C)$ which is the smoothed probability function to take care of words with 0 probabilities that may cause problems.

$\tilde{P}(w_i|C) = \frac{\text{Number of occurences of } w_i \text{ in all samples of class C} + 1}{\text{Total number of words in all samples of class C } + \text{ Vocabulary size}}$

####2.1

Find the vocabulary - list of unique words in all smses of ```data_train``` and assign it to the variable ```vocab```

In [ ]:
### Write your code here
all_words=[]
for i in data_train:
  all_words=all_words+i[1].split(" ")
vocab=list(set(all_words))
print(f'Length of vocab is {len(vocab)}')

Length of vocab is 8542


#### 2.2

For every word $w_i$ in vocab, find the count (total number of occurences) of $w_i$ in all smses of type ```spam```. Put these counts in a dictionary and assign it to a variable named ```dict_spam``` where key is the word $w_i$ and value is the count. <br>
In a similar way, create a variable called ```dict_ham``` which contains counts of each word in vocabulary in smses of type ```ham```. (This is only w.r.t samples in ```data_train```) 

In [ ]:
### Write your code here
spam_train=[]
ham_train=[]
for i in data_train:
  if(i[0]=="spam"):
    spam_train.extend(i[1].split(" "))
  else:
    ham_train.extend(i[1].split(" "))
dict_spam=counter(spam_train, lambda x: x)
dict_ham=counter(ham_train, lambda x: x)
print(dict_spam)

{'congratulations': 13, 'u': 115, 'can': 21, 'claim': 89, '2': 134, 'vip': 4, 'row': 1, 'a': 314, 'tickets': 3, 'c': 13, 'blu': 2, 'in': 61, 'concert': 1, 'november': 1, 'or': 159, 'gift': 16, 'guaranteed': 43, 'call': 268, '09061104276': 1, 'to': 550, 'tscs': 14, 'wwwsmsconet': 2, 'cost£375max': 1, '': 212, 'urgent': 49, 'we': 38, 'are': 62, 'trying': 13, 'contact': 48, 'you': 235, 'last': 9, 'weekends': 5, 'draw': 32, 'shows': 25, 'have': 112, 'won': 59, '£1000': 28, 'prize': 73, '09064017295': 1, 'code': 23, 'k52': 2, 'valid': 17, '12hrs': 12, '150p': 17, 'pm': 2, 'bought': 1, 'one': 5, 'ringtone': 19, 'and': 91, 'now': 145, 'getting': 3, 'texts': 10, 'costing': 1, '3': 18, 'pound': 4, 'offering': 1, 'more': 24, 'tones': 18, 'etc': 4, 'being': 6, 'contacted': 5, 'by': 31, 'our': 74, 'dating': 15, 'service': 50, 'someone': 14, 'know': 22, 'find': 18, 'out': 46, 'who': 48, 'it': 25, 'is': 122, 'from': 101, 'land': 15, 'line': 29, '09050000878': 1, 'pobox45w2tg150p': 2, 'new': 62, 'thi

In [ ]:
square=lambda x:x*x

def square(x):
  return x*x

####2.3

For every word $w_i$ in vocab, find the smoothed probability $\tilde{P}(w_i | \text{ spam })$ and put in a dictionary named ```dict_prob_spam```. 
In a similar way, define the dictionary ```dict_prob_ham``` which contains smoothed probabilities $\tilde{P}(w_i | \text{ ham })$

In [ ]:
### Write your code here
dict_prob_spam={}
dict_prob_ham={}
for i in vocab:
  dict_prob_spam[i]=(dict_spam.get(i,0)+1)/(len(spam_train)+len(vocab))
  dict_prob_ham[i]=(dict_ham.get(i,0)+1)/(len(ham_train)+len(vocab))


In [ ]:
x={'a':1,'b':2}
x.get('c',0)

0

###3. Prediction

We need to test our model on ```data_test``` . 
For each sample of ```data_test```, prediction procedure is as follows: 
- For all words common to the sample and vocabulary, find ```spam_score``` and ```ham_score```
- If ```spam_score``` is higher than ```ham_score```, then we predict the sample to be spam and vice versa.
- ```spam_score``` = $P(spam)*\tilde{P}(w_1 | \text{ spam }) *  \tilde{P}(w_2 | \text{ spam }) * \ldots$ where $w_1, w_2, \ldots$ are words which occur both in the test sms and vocabulary.
- Similary, ```ham_score``` = $P(ham)*\tilde{P}(w_1 | \text{ ham }) *  \tilde{P}(w_2 | \text{ ham }) * \ldots$ where $w_1, w_2, \ldots$ are words which occur both in the test sms and vocabulary. <br>
Here $P(spam) = \frac{\text{Number of samples of type spam in training set}}{\text{Total number of samples in training set}}$ <br>
Similarly, $P(ham) = \frac{\text{Number of samples of type ham in training set}}{\text{Total number of samples in training set}}$ <br>
(Note: The above is prediction procedure for a single sample in data_test) <br>
Write a function ```predict``` which does this.

####3.1

In [ ]:
def predict(text, dict_prob_spam, dict_prob_ham, data_train):
  """Function which predicts the label of the sms
  Inputs:
    text: string, sms
    dict_prob_spam: dictionary, contains dict_prob_spam as defined above
    dict_prob_spam: dictionary, contains dict_prob_ham as defined above
    data_train: list, list of tuples of type(label, sms), contains training dataset

  Outputs:
    prediction: string, one of two strings - either 'spam' or 'ham'
  """
  ### Write your code here
  p_spam=len(list(filter(lambda x:True if(x[0]=="spam") else False,data_train)))/len(data_train)
  p_ham=len(list(filter(lambda x: True if(x[0]=="ham") else False,data_train)))/len(data_train)
  spam_score=p_spam
  ham_score=p_ham
  for i in text.split(" "):
    spam_score=spam_score*dict_prob_spam.get(i,1)
    ham_score=ham_score*dict_prob_ham.get(i,1)
  if(spam_score>ham_score):
    prediction="spam"
  else:
    prediction="ham"

  return prediction

In [ ]:
print(sorted([(k, dict_spam[k]) for k in dict_spam.keys()], key = lambda x: x[1], reverse = True)[:20])
print(sorted([(k, dict_ham[k]) for k in dict_ham.keys()], key = lambda x: x[1], reverse = True)[:20])

[('to', 550), ('a', 314), ('call', 268), ('you', 235), ('', 212), ('your', 188), ('free', 177), ('or', 159), ('for', 159), ('the', 159), ('now', 145), ('2', 134), ('on', 128), ('txt', 128), ('is', 122), ('ur', 119), ('u', 115), ('have', 112), ('from', 101), ('text', 94)]
[('i', 1750), ('you', 1481), ('', 1325), ('to', 1275), ('the', 922), ('a', 855), ('u', 808), ('and', 694), ('in', 663), ('me', 638), ('my', 595), ('is', 591), ('it', 478), ('for', 419), ('of', 417), ('that', 381), ('im', 365), ('have', 359), ('your', 345), ('but', 342)]


####3.2

Now find accuracy of the model. Apply function predict to all the samples in data_test. <br>
$\text{accuracy} = \frac{\text{number of correct predictions}}{\text{size of test set}}$ <br>
Write the function accuracy which applies predict to all ```samples``` in data_test and returns ```accuracy```

In [ ]:
def accuracy(data_test, dict_prob_spam, dict_prob_ham, data_train):
  """Function which finds accuracy of model
  Inputs:
    data_test: list, contains tuples of data (label, sms) 
    dict_prob_spam: dictionary, contains dict_prob_spam as defined above
    dict_prob_spam: dictionary, contains dict_prob_ham as defined above
    data_train: list, list of tuples of type(label, sms), contains training dataset


  Outputs:
    accuracy: float, value of accuracy
  """
  ### Write your code here
  correct = 0
  for i in data_test:
    if(i[0] == predict(i[1], dict_prob_spam, dict_prob_ham, data_train)):
      correct += 1
  accuracy = correct/len(data_test)
  return accuracy

In [ ]:
accuracy(data_test, dict_prob_spam, dict_prob_ham, data_train)

0.9811659192825112